version: '3'
services:
  redis:
    image: redis
    command: redis-server --requirepass SECRET_PASSWORD
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_password
      POSTGRES_DB: db
    ports:
      - "5432:5432"