server:
  servlet:
    context-path: /api

spring:

  redis:
    host: localhost
    password: SECRET_PASSWORD

  datasource:
    username: root
    password: root_password
    url: jdbc:postgresql://localhost:5432/db
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
